### ISSUE TITLE
Switch out header assets

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/omeka-home#17]
Replace placeholder "Exhibit" image with assets from Phil (background image + title graphic)

**Comment by StudioZut** [comment]
Replaced on both index.php and template.php

**Comment by GrandPanjandrum** [comment]
#header-contents max-width is set to 1100px; too narrow! Background is not extending to adequate viewport width for screens.

**Comment by StudioZut** [comment]
I removed the max-width constraint for #header-contents, fixed. Feel free to re-open tickets like this going forward, that will make sure they are on my radar.
