### ISSUE TITLE
Sticky footer 

### ISSUE THREAD

**Issue by GrandPanjandrum** [gwu-libraries/omeka-home#19]
Footer needs to be sticky to bottom of viewport to account for pages with minimal content.

http://getbootstrap.com/examples/sticky-footer/ as a possible fix?

**Comment by StudioZut** [comment]
Also, adjust footer max-width to match new header max-width

**Comment by StudioZut** [comment]
Keeping the footer content at current max-width to preserve the current layout of the footer info.
